# Generated by Django 4.2.20 on 2025-03-21 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kelas_logmasukstudent_siswa_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ujian', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ujian_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('pilihan_a', models.CharField(max_length=200)),
                ('pilihan_b', models.CharField(max_length=200)),
                ('pilihan_c', models.CharField(max_length=200)),
                ('pilihan_d', models.CharField(max_length=200)),
                ('jawaban_benar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='accounts.ujian')),
            ],
        ),
    ]
