# Generated by Django 4.2.20 on 2025-04-14 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ujian_soal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='durasi_menit',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='ujian',
            name='waktu_mulai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ujian',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HasilUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('tanggal_selesai', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ujian')),
            ],
            options={
                'unique_together': {('siswa', 'ujian')},
            },
        ),
    ]
