# Generated by Django 4.2.20 on 2025-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ujian_durasi_menit_ujian_waktu_mulai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='voice_model',
            field=models.FileField(blank=True, null=True, upload_to='voice_models/'),
        ),
    ]
