# Generated by Django 4.2.20 on 2025-04-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_siswa_voice_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('FACE_VERIFY_ATTEMPT', 'Face Verification Attempt'), ('FACE_VERIFY_SUCCESS', 'Face Verification Success'), ('FACE_VERIFY_FAIL', 'Face Verification Fail'), ('VOICE_VERIFY_ATTEMPT', 'Voice Verification Attempt'), ('ACCOUNT_LOCKED', 'Account Locked')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
