# Generated by Django 4.2.20 on 2025-04-21 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=1)),
                ('waktu_jawab', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.soal')),
            ],
            options={
                'unique_together': {('siswa', 'soal')},
            },
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
