# Generated by Django 4.2.20 on 2025-04-21 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jawabansiswa_delete_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('MATCH', 'Match'), ('MISS_MATCH', 'Miss Match'), ('PROCTORING_CHECK', 'Proctoring Check')], max_length=20)),
                ('description', models.TextField()),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ujian')),
            ],
        ),
    ]
