# Generated by Django 4.2.20 on 2025-04-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_proctoringlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringlog',
            name='event_type',
            field=models.CharField(choices=[('MATCH', 'Match'), ('MISS_MATCH', 'Miss Match'), ('ERROR', 'Error')], max_length=20),
        ),
    ]
