# Generated by Django 4.2.20 on 2025-04-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_proctoringlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='voice_threshold',
            field=models.FloatField(default=-50.0),
        ),
    ]
