# Generated by Django 4.2.20 on 2025-04-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_siswa_voice_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='voice_model',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='voice_threshold',
        ),
    ]
