# Generated by Django 4.2.20 on 2025-05-03 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_voicedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicedata',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='voicedata',
            name='scaler_model',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicedata',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VoiceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_samples/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
