# Generated by Django 4.2.20 on 2025-05-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_voicedata_audio_file_voicedata_scaler_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicedata',
            name='threshold',
        ),
    ]
