# Generated by Django 4.2.20 on 2025-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_voicedata_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicedata',
            name='threshold',
            field=models.FloatField(default=-1000.0),
        ),
    ]
