# Generated by Django 4.2.20 on 2025-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userface'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicedata',
            name='margin',
            field=models.FloatField(default=10.0),
        ),
    ]
