# Generated by Django 4.2.20 on 2025-05-18 09:23

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_voicedata_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AugmentedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.user_face_path)),
                ('augment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='augmented_images', to='accounts.userface')),
            ],
        ),
    ]
