# Generated by Django 4.2.20 on 2025-05-19 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_augmentedface'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face_tests/%Y/%m/%d/')),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_test_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
